### ISSUE TITLE
Add support for PDF data

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#186]
**Is your feature request related to a problem? Please describe.**

PDF data is actually somewhat common in the EHR space and used in many datasets. We need support to read PDF data.

**Describe the solution you would like**

https://github.com/chezou/tabula-py is our best bet.

**Comment by Zethson** [comment]
@Imipenem sadly need this "urgently" because of the tuberculosis data, but this should be implement extremely quickly. Therefore, I added it to 0.1. Just grab some random PDF dataset (maybe tabular-py has examples) & call the read function when the extension is PDF. the Pandas dataframe is then easily handled.

**Comment by Imipenem** [comment]
@Zethson , tabula-py seems to work for some of the provided test pdfs, but not for all of them (at least not for all included in tabula-java repo: https://github.com/tabulapdf/tabula-java/tree/master/src/test/resources/technology/tabula). 

I can see some options here:

1.) Tabula-py lets us pass a `guess` parameter, which does some weird stuff and may or may, may improve or even worsen parsed result. So when inital parsing fails or does not produces sufficient results, we could try it using this parameter.

2.) If nothing worked sufficiently, tabula-py can parse and save the pdf to .csv files. I do not know though, if this will improve results (I doubt it, because they use the same parsing functions as the "vanilla" parsing).

So either way, we can and will support parsing pdf, but the results may not be as good as with other file formats.

**Comment by Zethson** [comment]
> 1.) Tabula-py lets us pass a guess parameter, which does some weird stuff and may or may, may improve or even worsen parsed result. So when inital parsing fails or does not produces sufficient results, we could try it using this parameter.

fine with me

> EDIT: Second point: What do you think about support for parsing multiple pdf files from a directory (like we have for csv for example). This will get quickly complicated, as each pdf themselves can contain multiple tables etc..
> I mean, there are many tools out there to combine multiple pdfs into one pdf in reasonable time, so we COULD force users to pass a single pdf file? Any thoughts on this?

Maybe we just need to see some real data beforehand. I'd open an issue for this and only support single PDF for now

**Comment by Imipenem** [comment]
> fine with me

will print a warning as well, that this may worsen results and , in case, it would be useful to open an issue at ehrapy.

> Maybe we just need to see some real data beforehand

Yes, sound good. I'd open an issue for this and only support single PDF for now
