### ISSUE TITLE
encoding tests warnings

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#349]
```
tests/preprocessing/test_encode.py::TestEncode::test_custom_encode_again_single_columns_encoding
tests/preprocessing/test_encode.py::TestEncode::test_custom_encode_again_multiple_columns_encoding
  /home/zeth/PycharmProjects/ehrapy/ehrapy/preprocessing/encoding/_encode.py:690: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
    type_first_nan = original_values[np.where(original_values != np.nan)][0]
```

We should resolve them

**Comment by Imipenem** [comment]
See https://github.com/numpy/numpy/issues/6784 and https://stackoverflow.com/questions/40659212/futurewarning-elementwise-comparison-failed-returning-scalar-but-in-the-futur.

Thats because we have to type cast the original values in uns. Guess for now we can go with it because it seems there is no easy fix in our situation, it seems.

**Comment by Zethson** [comment]
That's crazy.
