### ISSUE TITLE
Error 404 when trying to edit the docs

### ISSUE THREAD

**Issue by namsaraeva** [theislab/ehrapy#408]
**Describe the bug**

When I tried to click on the "edit" icon on the top right corner in https://ehrapy.readthedocs.io/en/latest/usage/usage.html (does not matter which method page), I got the 404 Page not found error. It apparently looks for the .rst files in ehrapy/docs/usage, but these do not exist. 

**To Reproduce**

1. Go to https://ehrapy.readthedocs.io/en/latest/usage/usage.html
2. Click on the edit icon on a random method page
3. You'll get the 404 Error page

**Expected behavior**
I guess the user should be able to see the source code (the method itself and the example in the docs)

**Comment by Imipenem** [comment]
The source code of each function contains the docstring which is parsed by the doc setup when setting up the docs; so this is a dynamic process rather than a static one with parsing a single `.rst` file or similar. So by clicking the `source` link next to the method signature, it shows you everything (since docstring == doc basically). So maybe we should find a way to simply delete the edit button on a single function docs page at all?
Am I missing something @Zethson ?

**Comment by Zethson** [comment]
It's an issue of using markdown instead of rst. This can be fixed.  Tuesday, 13 September 2022, 08:54PM +02:00 from Philipp Ehmele  ***@***.*** :

**Comment by Imipenem** [comment]
> It's an issue of using markdown instead of rst.

What's the issue here?

**Comment by Zethson** [comment]
We're not pushing the rst files and only the markdown files exist. So the link goes to nowhere.  Tuesday, 13 September 2022, 09:02PM +02:00 from Philipp Ehmele  ***@***.*** :

**Comment by Zethson** [comment]
Since we don't upload the generated rst files to the repository because we generate them on the fly by translating the markdown into the rst files that are actually rendered.

Think it would be tricky and messy to fix this. Hence, I removed the edit button for now.
