### ISSUE TITLE
Reduce `_move_columns_to_obs` and `move_to_obs` to one method

### ISSUE THREAD

**Issue by namsaraeva** [theislab/ehrapy#410]
**Is your feature request related to a problem? Please describe.**

I noticed that there are two methods for moving to `obs`: `_move_columns_to_obs` and `move_to_obs` that are slightly different: the former one is used for internal purposes and the latter is exposed via API to users.

**Describe the solution you would like**

I would like to merge those two methods to a single one to reduce redundancy in the code. `move_to_obs` would then accept not only an AnnData object, but a pd.DataFrame.

**Comment by Imipenem** [comment]
Good question! I mean from a users perspective it wouldn't make muche sense to move sth. to `obs` since there is no `obs` in a pandas dataframe. 

That said, I'd prefer having two functions (one accepting anndata, the other one a pandas dataframe), but let them share their body (a single function that does the moving) with a quick type check in both functions to ensure they are of type anndata/pandas dataframe. 

Sounds good? Any other ideas?

**Comment by Zethson** [comment]
Yes, please go for it :)

**Comment by Zethson** [comment]
@Imipenem what about dispatching this function? Once for AnnData and once for Pandas DF?

**Comment by Zethson** [comment]
Turns out that the Pandas DF method is only used once and therefore singledispatching this and making it public would only increase the complexity. Hence, I removed the Pandas version.
