### ISSUE TITLE
Add var type retrospectively

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#637]
### Description of feature

I just ran into the situation where I got an AnnData object which already had encoded data (label encoded) and now I have to manually create the `var` column types (`numeric`, `non-numeric`). I was wondering whether we should offer a convenience function here that will try to guess the column types retrospectively and annotate the var?

Basically just extracting this from `encode` and exposing it with the API

**Comment by Zethson** [comment]
@Lilly-May also ran into this and suggests to validate whether these keys exist early enough and guide the user through fixing it.

**Comment by Lilly-May** [comment]
I was just thinking about this a bit more and here's my suggestion on how to tackle this issue:

**Summary of the problems we're facing:**
- Already encoded data are missing the `adata.var["ehrapy_column_type"]` annotation that is created when calling `ep.pp.encode`, so one has to manually create the var annotation for downstream processing.
- The `adata.var["ehrapy_column_type"]` annotation stores whether a feature is numerical or not, but that doesn't always align perfectly with the continuous/categorical annotation. For instance, a disease flag might be represented as 0 or 1, treated as numerical data, but conceptually it remains categorical. This distinction is important e.g. for downstream bias detection and feature importance calculations.

**Suggestion on how to tackle this:**
We create a new method `ep.pp.feature_specifications` (or `feature_datatypes`?) that stores either the label `continuous` or the label `categorical` for each feature. The method attempts to infer this information: If ehrapy datatypes (`adata.var["ehrapy_column_type"]`, created during encoding) are presented, we can infer some labels from there. Otherwise, in general, numerical implies continuous features, except for some special cases we test for (such as only 0 and 1 values are present, then we save it as categorical). At the end, we print a table with each feature and the detected type. Users must then check the datatypes, and if something is wrong, correct it.

**Discussion points:**
1. How do we name that `var` annotation? We already have `ehrapy_column_type` for the annotation from encoding, but I would consider changing that to something like `encoding_feature_type` and then adding the new continuous/categorical annotation as something else (just `feature_type`?).
2. If a feature was detected incorrectly (which is likely to happen for at least one feature in the dataset), how is the user supposed to correct it? By setting `adata.var["whatever_we_call_this"]["feature1"]="continuous"`? The downside is that someone could introduce a typo there (e.g., "continous"), potentially affecting downstream analyses. So, should we instead introduce another method, `flip_annotation`, that simply takes a list of falsely detected features as input and flips the annotation (which is conveniently possible as we only have two options here)?
3. In downstream methods that depend on that annotation (e.g., `feature_importances` and `bias_detection`), should we require the user to call that method first (which would save a lot of if/else cases and type guessing) and simply throw an error if `adata.var["whatever_we_call_this"]` is not present?
4. Do we also attempt to set the encoding datatypes in that method if they are not already present? This would address the first problem stated above. However, I'm wondering which downstream methods actually use that annotation and if what the methods really need is, in fact, the continuous/categorical annotation?

@Zethson, @eroell I would love your input on this!😊

**Comment by Zethson** [comment]
Thank you very very much @Lilly-May ! It's heart warming to see someone summarizing the problem first before commenting on it :)

**A few general notes on this topic before I add my thoughts on your comments:**

Currently there's several ways to get an AnnData object ready for use with ehrapy.

One can either create an `AnnData` object directly using the `anndata` package and then encode it, or one can use one of our readers and then encode it. **To me, it's important that we support both ways as first class and ideally without the user noticing anything.** I also want to reduce the number of fail points for ehrapy functions and guide users to preparing/fixing their object trivially. One way of at least checking for whether the object is ready is to use a decorator for ehrapy functions which checks for the required keys (e.g. `adata.var["ehrapy_column_type"]` and maybe even their values)

Moreover, there might be additional complexity with **date types** which are often handled differently with Pandas etc. These are also detected during encoding and we never want them in `X`. Just food for thought and we should not forget about them.

**On your suggested solution**

>  We create a new method ep.pp.feature_specifications (or feature_datatypes?) that stores either the label continuous or the label categorical for each feature.

Just like I mention before, I am debating whether we should offer such a method solely in the public API or even run it automatically before any of the actual ehrapy functions are run (the decorator part). Ideally, we don't want the user to be able to use ehrapy without having all information stored.

>  The method attempts to infer this information: If ehrapy datatypes (adata.var["ehrapy_column_type"], created during encoding) are presented, we can infer some labels from there. 

It's probably better to move this out of the encoding and have this always run in some way (the decorator idea).

> Otherwise, in general, numerical implies continuous features, except for some special cases we test for (such as only 0 and 1 values are present, then we save it as categorical).

Yeah, these tests aren't always going to be right, but probably in 99% of the cases they will be. It's probably a matter of "integer values in ascending order without gaps" -> 1,2,3,4 indicates label encodet categoricals; 0, 5, 52 does not. Note that we can also use this information to already pre-populate some of the encoding stuff for later.

> At the end, we print a table with each feature and the detected type. Users must then check the datatypes, and if something is wrong, correct it.

https://ehrapy.readthedocs.io/en/latest/usage/anndata/ehrapy.anndata.type_overview.html#ehrapy.anndata.type_overview :) Prints it already nicely.

> a new method ep.pp.feature_specifications (or feature_datatypes?)

Note: I am not sure whether this should be in preprocessing or [anndata-utilities](https://ehrapy.readthedocs.io/en/latest/usage/usage.html#anndata-utilities) where it probably fits better. This is just at the end of the documentation and therefore a bit harder to find.

> How do we name that var annotation? We already have ehrapy_column_type for the annotation from encoding, but I would consider changing that to something like encoding_feature_type and then adding the new continuous/categorical annotation as something else (just feature_type?).

There might be a way to harmonize that just like we're trying to use it at the moment, no? If it's encoded, it has to be categorical and if not, it's continuous. But if we go through with my suggested idea, it might be easier if we divide it into two keys. We might need a rough API draft again to figure that out.
In any case, it'd probably be something like `feature_type` and `encoding` where the latter is only roughly `Literal["unencoded", "numerical", "one-hot", "label"]` which should span all cases. Note that one could infer the `feature_type` based on these values.

> If a feature was detected incorrectly (which is likely to happen for at least one feature in the dataset), how is the user supposed to correct it? By setting adata.var["whatever_we_call_this"]["feature1"]="continuous"? The downside is that someone could introduce a typo there (e.g., "continous"), potentially affecting downstream analyses. So, should we instead introduce another method, flip_annotation, that simply takes a list of falsely detected features as input and flips the annotation (which is conveniently possible as we only have two options here)?

If we were to use a decorator, we could quickly verify that there are no typos aka only the expected `Literal`. Flipping is not attractive if we need to also take care of `dates`... although I guess they should be easier to detect (I nevertheless remember @Imipenem having some trouble with them).

> In downstream methods that depend on that annotation (e.g., feature_importances and bias_detection), should we require the user to call that method first (which would save a lot of if/else cases and type guessing) and simply throw an error if adata.var["whatever_we_call_this"] is not present?

Decorator says hello!

> Do we also attempt to set the encoding datatypes in that method if they are not already present? This would address the first problem stated above. However, I'm wondering which downstream methods actually use that annotation and if what the methods really need is, in fact, the continuous/categorical annotation?

Hello, it's me, Dec, the happy decorator.

**Final remark**

I actually didn't read your response before suggesting the `decorator` idea so I guess this would solve if not all of our concerns?

**Comment by eroell** [comment]
Cool discussion!

**My understanding (correct me if I miss a point)**
- Generally speaking we want to add public facing function for continuous vs categorical feature labelling in an AnnData object where this information is not yet available
- Hardest case is that this is even encoded already

**Inputs on how to tackle**
> We create a new method ep.pp.feature_specifications (or feature_datatypes?)

I think a public facing function is a good idea; if users read e.g. from csv (or anndata, which is actually not doing the type inference at the moment right?^^) they won't need it. But if they build an anndata on the fly, they could then.

> automatically before any of the actual ehrapy functions are run (the decorator part)

Have a decorator - amazing. Having it check the values and their validity - amazing. In favor of a decorator doing an error  (and maybe saying call the public <do type inference of your data> function) rather than going into the mess & risks on doing inference itself. If missing, warning the user and telling to do type inference seems better to me than silently slide that in at arbitrary stages.

**Inputs on discussion points**
> 1. How do we name that var annotation? 

Are the 3 current "numeric", "non_numeric", "non_numeric_encoded" not enough?
If yes, +1 from my side for having 2 columns, `feature_type` and `encoding`. I love disentanglement.

> 2. If a feature was detected incorrectly

Hm having a flipping function doesn't sound too bad actually. Wouldnt hinder users from doing it manually if they prefer. In any case, validate dataframe before relevant function calls with decorator.

+1 for checking the validity of that column in decorator, and let user do replacement using pandas api. I see tho that a bit of user guidance could be needed. Mention in an early tutorial?

> Flipping is not attractive if we need to also take care of dates

Not sure I get, if someone wants to flip a date?

> 3. In downstream methods that depend on that annotation

Decorator validation

> 4. Do we also attempt to set the encoding datatypes in that method if they are not already present?

Not sure I get it; basically what to do if a function is called on an anndata without the type information? Then the decorator would by my answer here, too :)

**Comment by Lilly-May** [comment]
Thanks for your input @Zethson and @eroell!

Let me summarize the main points, and please correct me if I misunderstood your ideas.

- After preprocessing, the adata should have a `feature_type` key
- We have a decorator that checks if the `feature_type` is stored in `var` (and filled with correct labels)
- We introduce a function `ep.pp.feature_specifications` (name might change) that guesses the `categorical`/`continuous` (potentially also `date`) labels as far as possible and prints a table of the results. The user should then check and, if necessary, correct the annotations.

**Points up for discussion:**
- Do we use the decorator for every `ehrapy.tools` function or just the ones that need the annotation?
- Is the decorator only testing if `adata.var['feature_type']` is present, or is it also running the detection method if it's not present? I would vote for not automatically running the inference because then, how do we print the data types and request users to check and correct if necessary if immediately afterward the actual function (that has the decorator) is run?
- Do we add a `flip_annotation` function? I think this depends on whether we have the three labels (`continuous`/`categorical`/`date`) or just the former two. In the latter case, I would add the function for convenience.
- Do we also need to enforce the adata to have the `encoding` annotation in `var` by incorporating that into the decorator? I just took a brief look, and it seems like `_rank_feature_groups` and `_imputation` use the encoding annotation, but I'll check whether what's actually needed here is information on categorical/continuous labels rather than on the encoding. In any case, is there a clear reason why we should require the `encoding` annotation to be there? Because that could be inconvenient for already encoded data.

**Comment by Zethson** [comment]
> After preprocessing, the adata should have a feature_type key

Maybe even **before preprocessing** because the preprocessing functions need this information.

> We introduce a function ep.pp.feature_specifications (name might change) that guesses the categorical/continuous (potentially also date) labels as far as possible and prints a table of the results. The user should then check and, if necessary, correct the annotations.

I would consider having this in `ep.ad`. I really don't know whether we should even expose this function explicitly to the users. I would actually go as far as having the decorator do this already (so not just check, but actually run it if the keys are missing). My reasoning is that most other functions depend on the existence of these keys anyways, so why not force the users to fix it immediately? https://ehrapy.readthedocs.io/en/latest/usage/anndata/ehrapy.anndata.type_overview.html#ehrapy.anndata.type_overview already does the printing. However, this does not scale to 1000+ variables. We might have to consider showing users somehow only the ambiguous or more difficult cases.

> Do we use the decorator for every ehrapy.tools function or just the ones that need the annotation?

It's not just tools but also the preprocessing functions that can make use of this information. Especially in the future I expect more and more to make use of that. Also some plots potentially? If it's super fast, we can probably add it everywhere. Unlikely that people try to plot without running a preprocessing function or a tool, but never underestimate the ability of users to do weird things.

> Is the decorator only testing if adata.var['feature_type'] is present, or is it also running the detection method if it's not present? I would vote for not automatically running the inference because then, how do we print the data types and request users to check and correct if necessary if immediately afterward the actual function (that has the decorator) is run?

Voting for running it as outlined above. The decorator could throw an error? Not pretty but maybe one with a super condensed stacktrace.

> Do we add a flip_annotation function? I think this depends on whether we have the three labels (continuous/categorical/date) or just the former two. In the latter case, I would add the function for convenience.

I vote no.

> Do we also need to enforce the adata to have the encoding annotation in var by incorporating that into the decorator? I just took a brief look, and it seems like _rank_feature_groups and _imputation use the encoding annotation, but I'll check whether what's actually needed here is information on categorical/continuous labels rather than on the encoding. In any case, is there a clear reason why we should require the encoding annotation to be there? Because that could be inconvenient for already encoded data.

Both of those probably only need categorical/continuous as information. I don't recall whether we also need the specific encoding annotation. You can probably just check where it's stored and search the repository to figure that out?

**Comment by Lilly-May** [comment]
> I would consider having this in ep.ad. I really don't know whether we should even expose this function explicitly to the users. I would actually go as far as having the decorator do this already (so not just check, but actually run it if the keys are missing). My reasoning is that most other functions depend on the existence of these keys anyways, so why not force the users to fix it immediately?

I agree that we should force the users to do/fix the type specification. But if we have a decorator that also runs the detection if the key is missing from `var`, how do we then prompt the user to fix annotations? Maybe I misunderstand what you mean but we would basically run it in the background without exposing the user to it? Because this will likely introduce some mis-annotation and if whatever function the user actually called is then run immediately afterwards, how would the user be prompted to check and correct the annotations?

**Comment by eroell** [comment]
Thanks for the summary again!

General agreement with Lukas answers above.
Only that I'd vote for having the `flip_annotations` - but we can also keep it just in mind, and add later once need would become apparent. :)

**Comment by Zethson** [comment]
> Only that I'd vote for having the flip_annotations - but we can also keep it just in mind, and add later once need would become apparent. :)

My reasoning is that ehrapy already has a shit ton of methods and we're currently adding even more. Also, if we ever need more types (for whatever reason) at some point (free text, dates, [...]?) then this method becomes obsolete anyways.

**Comment by Lilly-May** [comment]
Thanks for all your input!
I've merged this issue with the related issues #649 and #662 into the new issue #701 for a better overview. Therefore, I'll close this issue here.
