### ISSUE TITLE
Pip install for recent version 0.8.0 reports wheel building error

### ISSUE THREAD

**Issue by mhaist94** [theislab/ehrapy#738]
### Report

Hi all,
thanks for the recent updates to your fantastic tool!
Just tried pulling the most recent 0.8.0 version using pip install ehrapy but ran into some issues with building wheel for blosc. Not sure if this is a reproducible issue but havent been able to fix it so far. 
Ran into this issue both on a MAC OS and WINDOWS Server 2019. 
<img width="666" alt="image" src="https://github.com/theislab/ehrapy/assets/115837960/fda72c8c-8460-42c8-b9db-cfe3899fcf54">
<img width="668" alt="image" src="https://github.com/theislab/ehrapy/assets/115837960/33319e36-e516-4dbc-aa88-193a6fba4ee9">

Maybe you have an idea what might be the issue here?
Thanks all!
Max

**Comment by Zethson** [comment]
Dear @mhaist94,

thank you for the kinds words! We're just getting started and still have so many plans...
I have never seen this before. Let's focus on the Mac first. Could you please tell me:

1. Which Mac + CPU architecture?
2. Which Python version + did you use a clean environment?
3. Could you please paste the traceback as text so that I can search it more easily?

Then we go from there. Thank you!

**Comment by Zethson** [comment]
https://github.com/Blosc/python-blosc/issues/325

Are you trying to use Python 3.12?

**Comment by Zethson** [comment]
> Stupid me....

Not at all! I, as a developer who knew about the lack of Python 3.12 support (not our fault), should have bounded the Python versions to less than 3.12. You would have gotten a more informative error then.

Generally, I'm super eager to get feedback of yours by the way. Please open issues if you have feature requests, found bugs, or have any other comments.

Thanks!
